// test-harness/main.ts
import { ARRuntime, type RuntimeDocument } from "../src";
import { TestbedClient } from "./client";
import { compareRequest, parseInputs, requestsAddedSince, type ObservedRequest, type TestCase } from "./logic";

const element = <T extends HTMLElement>(selector: string): T => { const found = document.querySelector<T>(selector); if (!found) throw new Error(`Harness の要素 ${selector} がありません。`); return found; };
const connection = element<HTMLFormElement>("#connection"); const origin = element<HTMLInputElement>("#origin"); const state = element<HTMLElement>("#connection-state"); const info = element<HTMLElement>("#info"); const cases = element<HTMLSelectElement>("#cases"); const caseView = element<HTMLElement>("#case"); const load = element<HTMLButtonElement>("#load"); const documentView = element<HTMLElement>("#document"); const inputs = element<HTMLTextAreaElement>("#inputs"); const invoke = element<HTMLButtonElement>("#invoke"); const result = element<HTMLElement>("#result"); const runtimeError = element<HTMLElement>("#runtime-error"); const expected = element<HTMLElement>("#expected"); const observed = element<HTMLElement>("#observed"); const comparison = element<HTMLElement>("#comparison"); const reset = element<HTMLButtonElement>("#reset"); const error = element<HTMLElement>("#error");
let client: TestbedClient | undefined; let availableCases: readonly TestCase[] = []; let selected: TestCase | undefined; let runtimeDocument: RuntimeDocument | undefined;
const show = (target: HTMLElement, value: unknown): void => { target.textContent = value === undefined ? "" : JSON.stringify(value, null, 2); };
const clearInvocation = (): void => { result.textContent = ""; runtimeError.textContent = ""; observed.textContent = ""; comparison.textContent = ""; };
const fail = (value: unknown): void => { error.textContent = value instanceof Error ? `${value.name}: ${value.message}` : "不明なエラーです。"; };

connection.addEventListener("submit", async (event) => { event.preventDefault(); error.textContent = ""; state.textContent = "接続中…"; try { const next = TestbedClient.create(origin.value); const nextInfo = await next.info(); const nextCases = await next.cases(); client = next; availableCases = nextCases; cases.replaceChildren(...nextCases.map((item) => new Option(`${item.id} — ${item.description}`, item.id))); cases.disabled = false; reset.disabled = false; state.textContent = "接続済み"; show(info, nextInfo); selectCase(nextCases[0]); } catch (value) { client = undefined; state.textContent = "接続失敗"; fail(value); } });
cases.addEventListener("change", () => selectCase(availableCases.find((item) => item.id === cases.value)));
load.addEventListener("click", async () => { if (!selected?.documentUrl) return fail(new Error("選択したケースに documentUrl がありません。")); error.textContent = ""; runtimeError.textContent = ""; runtimeDocument = undefined; try { const loaded = await new ARRuntime().load(selected.documentUrl); runtimeDocument = loaded; show(documentView, { url: loaded.url, category: loaded.category, profileClaims: loaded.profileClaims, capabilities: loaded.capabilities }); invoke.disabled = !selected.capabilityId || !loaded.getCapability(selected.capabilityId); } catch (value) { documentView.textContent = ""; show(runtimeError, value instanceof Error ? { phase: "load", name: value.name, message: value.message } : value); } });
invoke.addEventListener("click", async () => { if (!client || !selected || !runtimeDocument || !selected.capabilityId) return; clearInvocation(); error.textContent = ""; let requestsBeforeInvocation: readonly ObservedRequest[]; try { requestsBeforeInvocation = await client.requests(); } catch (value) { fail(value); return; } try { const capability = runtimeDocument.getCapability(selected.capabilityId); if (!capability) throw new Error(`Capability ${selected.capabilityId} が RuntimeDocument にありません。`); show(result, await capability.invoke(parseInputs(inputs.value))); } catch (value) { const diagnostic = value instanceof Error ? { name: value.name, message: value.message } : value; show(runtimeError, diagnostic); } try { await showCurrentInvocationRequest(client, selected, requestsBeforeInvocation); } catch (value) { fail(value); } });
reset.addEventListener("click", async () => { if (!client) return; try { await client.reset(); clearInvocation(); state.textContent = "観測履歴をリセットしました"; } catch (value) { fail(value); } });
function selectCase(next: TestCase | undefined): void { selected = next; runtimeDocument = undefined; documentView.textContent = ""; clearInvocation(); if (!next) return; inputs.value = JSON.stringify(next.inputs ?? {}, null, 2); inputs.disabled = false; load.disabled = !next.documentUrl; invoke.disabled = true; show(caseView, next); show(expected, next.expected); }
/** Invocation 前後で増えたリクエストだけを表示・比較し、古い履歴を結果に混ぜません。 */
async function showCurrentInvocationRequest(testbed: TestbedClient, testCase: TestCase, before: readonly ObservedRequest[]): Promise<void> { const latest = requestsAddedSince(before, await testbed.requests()).at(-1); show(observed, latest); show(comparison, compareRequest(testCase.expected, latest)); }
